name: Build WIC LIVE

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Bun
      run: |
        irm bun.sh/install.ps1|iex
        echo "C:\Users\runneradmin\.bun\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      shell: powershell

    - name: Install Bun modules
      run: bun install
      shell: powershell

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build Tauri app with Bun
      env:
        TAURI_PRIVATE_KEY: ${{ secrets.SIGN_KEY }}
        WICLIVE_ENV: production
      run: bun run tauri build
      shell: powershell
