name: Build and Release WIC LIVE

on:
  push:
    branches: [ 2.0.0-beta ]

jobs:
  build-and-release-beta:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node/NPM
        uses: actions/setup-node@v4      

      - name: Install node modules
        run: npm install
        shell: powershell

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Tauri app
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ""
          WICLIVE_ENV: testing
        run: npm run tauri build -- --debug
        shell: powershell

      - name: Get latest release
        id: get_latest_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
          release_id=$(echo $latest_release | jq -r .id)
          echo "::set-output name=release_id::$release_id"
        shell: bash

      - name: Upload debug build EXE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_latest_release.outputs.release_id }}/assets?name=wiclive_x64-setup-debug.exe
          asset_path: ${{ github.workspace }}/src-tauri/target/debug/bundle/nsis/WIC LIVE_${{ steps.get_version.outputs.version }}_x64-setup.exe
          asset_name: wiclive_x64-setup-debug.exe
          asset_content_type: application/octet-stream
