name: Build and Release WIC LIVE

on:
  push:
    branches: [ master ]

jobs:
  install-tools:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Bun
        run: |
          irm bun.sh/install.ps1 | iex
          echo "C:\Users\runneradmin\.bun\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: powershell

      - name: Install Bun modules
        run: bun install
        shell: powershell

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Get version from tauri.conf.json
        id: get_version
        run: |
          $version = (Get-Content ./src-tauri/tauri.conf.json -Raw | ConvertFrom-Json).package.version
          echo "::set-output name=version::$version"
        shell: powershell

  build-app:
    needs: install-tools
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Tauri app with Bun
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ""
          WICLIVE_ENV: production
        run: bun run tauri build
        shell: powershell

  create-release:
    needs: build-app
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.install-tools.outputs.version }}
          release_name: Release ${{ needs.install-tools.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset EXE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/src-tauri/target/release/bundle/nsis/wiclive_${{ needs.install-tools.outputs.version }}_x64-setup.exe
          asset_name: wiclive_${{ needs.install-tools.outputs.version }}_x64-setup.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset NSIS ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/src-tauri/target/release/bundle/nsis/wiclive_${{ needs.install-tools.outputs.version }}_x64-setup-nsis.zip
          asset_name: wiclive_${{ needs.install-tools.outputs.version }}_x64-setup-nsis.zip
          asset_content_type: application/zip

      - name: Upload Release Asset NSIS ZIP SIG
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/src-tauri/target/release/bundle/nsis/wiclive_${{ needs.install-tools.outputs.version }}_x64-setup-nsis.zip.sig
          asset_name: wiclive_${{ needs.install-tools.outputs.version }}_x64-setup-nsis.zip.sig
          asset_content_type: application/octet-stream

  set-up-version:
    needs: create-release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate version.json in the docs directory
        run: |
          $version = "${{ needs.install-tools.outputs.version }}"
          $url = "https://github.com/${{ github.repository }}/releases/download/$version/wiclive_$version_x64-setup.exe"
          $signaturePath = "./src-tauri/target/release/bundle/nsis/wiclive_${{ needs.install-tools.outputs.version }}_x64-setup-nsis.zip.sig"
         
